# Generated by Django 3.2.9 on 2021-11-25 05:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 5, 51, 12, 190762, tzinfo=utc)),
        ),
    ]
