# Generated by Django 3.2.9 on 2021-11-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0002_alter_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='products/default.png', upload_to='products')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_product.product')),
            ],
        ),
    ]
