# Generated by Django 3.2.9 on 2021-11-15 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_product', '0003_auto_20211115_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='products/default.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='cart_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='seller_product.cart'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='picture',
            field=models.ImageField(default='products/default.png', null=True, upload_to='products'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='seller_product.orders'),
        ),
    ]
