# Generated by Django 3.2.9 on 2021-11-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0004_auto_20211115_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='products/default.png', null=True, upload_to='products'),
        ),
    ]
