# Generated by Django 3.2.9 on 2021-11-26 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0004_auto_20211126_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_of_sales',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 5, 12, 10, 969705, tzinfo=utc)),
        ),
    ]
