# Generated by Django 3.2.9 on 2021-11-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0005_alter_product_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='picture',
        ),
    ]
