# Generated by Django 3.2.9 on 2021-11-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0005_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='products/default.png', upload_to='products'),
        ),
    ]
