# Generated by Django 3.2.9 on 2021-11-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0006_auto_20211110_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
