# Generated by Django 3.2.9 on 2021-11-10 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_product', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
