# Generated by Django 3.2.9 on 2021-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0006_remove_productimage_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='icon',
            new_name='picture2',
        ),
        migrations.AddField(
            model_name='product',
            name='picture1',
            field=models.ImageField(default='products/default.png', upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture3',
            field=models.ImageField(default='products/default.png', null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture4',
            field=models.ImageField(default='products/default.png', null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
