# Generated by Django 3.2.9 on 2021-11-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0007_product_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wishlist',
            new_name='wishlist_user',
        ),
    ]
