# Generated by Django 3.2.9 on 2021-11-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0009_auto_20211116_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
