# Generated by Django 3.2.9 on 2021-11-19 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0011_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2021, 11, 26, 6, 9, 8, 212701, tzinfo=utc))),
                ('used', models.IntegerField(default=0)),
            ],
        ),
    ]
