# Generated by Django 3.2.9 on 2021-11-19 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0012_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 6, 13, 33, 594853, tzinfo=utc)),
        ),
    ]
