# Generated by Django 3.2.9 on 2021-11-19 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0013_auto_20211119_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2021, 11, 26, 9, 49, 28, 296214, tzinfo=utc))),
                ('used', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
