# Generated by Django 3.2.9 on 2021-11-23 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0014_auto_20211119_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture4',
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'poor'), (2, 'unsatisfactory'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 16, 27, 33, 29794, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller_product.product')),
            ],
        ),
    ]
