# Generated by Django 3.2.9 on 2021-11-21 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0014_auto_20211119_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('product_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, 'poor'), (2, 'unsatisfactory'), (3, 'average'), (4, 'good'), (5, 'excellent')], default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 8, 21, 39, 192763, tzinfo=utc)),
        ),
    ]
