# Generated by Django 3.2.9 on 2021-11-21 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0015_auto_20211121_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='image',
            field=models.ImageField(default='brands/wp6611732_wru2sc', upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 8, 41, 18, 137938, tzinfo=utc)),
        ),
    ]
