# Generated by Django 3.2.9 on 2021-11-23 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0015_auto_20211123_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 16, 38, 51, 381274, tzinfo=utc)),
        ),
    ]
