# Generated by Django 3.2.9 on 2021-11-23 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0016_auto_20211123_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 37, 48, 362313, tzinfo=utc)),
        ),
    ]
