# Generated by Django 3.2.9 on 2021-11-21 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0016_auto_20211121_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 8, 42, 56, 110644, tzinfo=utc)),
        ),
    ]
