<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-23 17:38
=======
# Generated by Django 3.2.9 on 2021-11-23 17:37
>>>>>>> parent of 6aeb868 (added model for product image)

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('seller_product', '0017_alter_coupon_expiry'),
=======
        ('seller_product', '0016_auto_20211123_2208'),
>>>>>>> parent of 6aeb868 (added model for product image)
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 38, 25, 767908, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 17, 37, 48, 362313, tzinfo=utc)),
>>>>>>> parent of 6aeb868 (added model for product image)
        ),
    ]
