# Generated by Django 3.2.9 on 2021-11-24 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0017_alter_coupon_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 14, 52, 26, 584051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
