# Generated by Django 3.2.9 on 2021-11-24 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seller_product', '0018_alter_coupon_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='picture',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 3, 26, 37, 907864, tzinfo=utc)),
        ),
    ]
