# Generated by Django 3.2.8 on 2021-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_email_otp_otpemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='picture',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
