# Generated by Django 3.2.9 on 2021-11-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_newuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, default='AKGEC 27th KM Milestone, Delhi - Meerut Expy, Ghaziabad, Uttar Pradesh 201009', max_length=200, null=True),
        ),
    ]
