# Generated by Django 3.2.8 on 2021-11-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_newuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='picture',
            field=models.ImageField(default='images/user.png', upload_to='images'),
        ),
    ]
