# Generated by Django 3.2.8 on 2021-11-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_newuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
    ]
