# Generated by Django 3.2.8 on 2021-10-31 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211031_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=150, null=True),
        ),
    ]
