# Generated by Django 3.2.8 on 2021-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_newuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
