# Generated by Django 3.2.8 on 2021-10-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
