# Generated by Django 3.2.8 on 2021-10-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_email', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
