# Generated by Django 3.2.9 on 2021-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211105_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
