# Generated by Django 3.2.8 on 2021-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
