# Generated by Django 3.2.8 on 2021-11-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_newuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
