# Generated by Django 3.2.9 on 2021-11-01 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_newuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
