# Generated by Django 3.2.8 on 2021-11-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_otp_time_created'),
        ('base', '0014_remove_newuser_user_name'),
    ]

    operations = [
    ]
